### ISSUE TITLE
Highly overlapped with existing study

### ISSUE THREAD

**Issue by iboing** [tkasarla/max-separation-as-inductive-bias#3]
Hi, the geometric structure revealed by the Lemma 1 and Theorem 1 in your paper has been totally given in Neural Collapse by the definition of a simplex equiangular tight frame, see [arXiv:2008.08186](https://arxiv.org/abs/2008.08186).

Besides, your method seems highly overlapped with the study [arXiv:2203.09081](https://arxiv.org/abs/2203.09081).

**Comment by tkasarla** [comment]
Thanks for the comment. Neural collapse was also pointed out in the reviewer discussion, and we have included a discussion to the original paper in our updated manuscript. I will update arxiv soon with the NeurIPS camera ready version.
